### ISSUE TITLE
hello_video

### ISSUE THREAD

**Issue by nagualcode** [rubu/RpiOmxTunnelReconfiguration#1]
Hello, this is great!
Could you provide a way to play any h264 video, using command line?
I am having problems with hello_video when I play videos with different reslution, because of omx tunnel.

**Comment by rubu** [comment]
Whoah, I never expected this to become handy for anyone:D 

Well as for command line tools - I do not know, I wrote this since gstreamer was not able to handle the resolution changes (maybe this has been fixed, I do not know). 

If you are planning to do make your own tool I'd suggest using ffmpeg/libav to handle the containers and then just feed NAL units to OMX.

**Comment by nagualcode** [comment]
Yes it is very useful!
I faced this problem with this program:
https://github.com/dtewksbury/video_server
It plays a folder of h264 videos, but if there is a change in resolution, the video server crashes.
It is a shame I dont know C and I cant go any further.

**Comment by rubu** [comment]
Well if you need to play videos that have different resolutions but each of the video has a constant one you could make a bash script that calls gstreamer on each one, waits till it finishes playing, launches next one, etc. etc.

**Comment by nagualcode** [comment]
I am playing local files, not streaming...
I will keep looking for it.
Thank you!
Please close the issue to keep your project git clean :)
